//! Verified bounded download staging and atomic part-file promotion.

use std::fs::{self, File, OpenOptions};
use std::io::{self, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};

use anyhow::{Context, anyhow, bail};
use sha2::{Digest, Sha256};

use super::GitHubReleaseClient;
use super::release::{AvailableRelease, MAX_EXECUTABLE_BYTES, validate_download_url};

#[cfg(test)]
mod tests;

/// Download one eligible asset and publish it only after both digest passes succeed.
///
/// Args:
///     client: Shared bounded GitHub transport facade.
///     release: Immutable release metadata selected by discovery.
///     nonce: Validated transaction identifier generated by the transaction owner.
///
/// Returns:
///     The staged path after streamed and post-sync verification on one open handle.
pub(super) fn download_verified(
    client: &GitHubReleaseClient,
    release: &AvailableRelease,
    nonce: &str,
) -> anyhow::Result<PathBuf> {
    let staged_path = crate::config::paths::update_staged_executable_path(nonce)
        .context("resolve canonical update staging path")?;
    validate_download_url(release.download_url(), release.release_tag())?;
    stage_verified_asset(
        client,
        release.download_url(),
        &staged_path,
        release.asset_size(),
        &release.asset_sha256(),
        "MoonTerminal-updater",
        MAX_EXECUTABLE_BYTES,
    )
}

impl GitHubReleaseClient {
    /// Bounded HTTPS client for an exact GitHub release-list URL.
    ///
    /// Args:
    ///     releases_url: Exact `https://api.github.com/repos/.../releases` endpoint.
    ///
    /// Returns:
    ///     A client that rejects plain HTTP and uses the same timeouts as self-update.
    pub(crate) fn for_github_releases(releases_url: &str) -> Self {
        Self::build(releases_url, true)
    }

    /// Download one GitHub release asset into `dest` after streamed and post-sync SHA-256 checks.
    ///
    /// Args:
    ///     download_url: Caller-validated HTTPS GitHub release-download URL.
    ///     dest: Final promotion path. Unique `.part` files are created beside it.
    ///     expected_size: Immutable size from release metadata.
    ///     expected_digest: Immutable SHA-256 from official checksum or GitHub digest.
    ///     user_agent: Product-specific User-Agent; the updater keeps `MoonTerminal-updater`.
    ///     max_bytes: Hard ceiling, never larger than the caller's policy.
    ///
    /// Returns:
    ///     `dest` after both digest passes and atomic rename.
    pub(crate) fn stage_verified_asset(
        &self,
        download_url: &str,
        dest: &Path,
        expected_size: u64,
        expected_digest: &[u8; 32],
        user_agent: &str,
        max_bytes: u64,
    ) -> anyhow::Result<PathBuf> {
        stage_verified_asset(
            self,
            download_url,
            dest,
            expected_size,
            expected_digest,
            user_agent,
            max_bytes,
        )
    }
}

/// Stage one verified GitHub asset beside `dest` using unique `.part` files.
fn stage_verified_asset(
    client: &GitHubReleaseClient,
    download_url: &str,
    dest: &Path,
    expected_size: u64,
    expected_digest: &[u8; 32],
    user_agent: &str,
    max_bytes: u64,
) -> anyhow::Result<PathBuf> {
    if expected_size == 0 || expected_size > max_bytes {
        bail!("release asset size is outside the allowed range");
    }
    let parent = dest
        .parent()
        .ok_or_else(|| anyhow!("staged executable has no parent directory"))?;
    ensure_plain_directory(parent)?;
    let (part_path, part_file) = create_unique_part(dest)?;
    let mut part = PartFile::new(part_path, part_file);
    download_into(
        client,
        download_url,
        expected_size,
        expected_digest,
        max_bytes,
        user_agent,
        part.file_mut(),
    )?;
    let part_path = part.path().to_path_buf();
    promote_verified_part(
        &part_path,
        part.file_mut(),
        dest,
        expected_size,
        expected_digest,
    )?;
    part.disarm();
    Ok(dest.to_path_buf())
}

/// Stream one response into the already-exclusive part file and verify its first hash.
fn download_into(
    client: &GitHubReleaseClient,
    download_url: &str,
    expected_size: u64,
    expected_digest: &[u8; 32],
    max_bytes: u64,
    user_agent: &str,
    part_file: &mut File,
) -> anyhow::Result<()> {
    let mut response = client
        .agent
        .get(download_url)
        .header("Accept", "application/octet-stream")
        .header("User-Agent", user_agent)
        .call()
        .context("download update asset")?;
    let status = response.status().as_u16();
    if !(200..300).contains(&status) {
        bail!("GitHub update asset returned HTTP {status}");
    }
    copy_verified_bounded(
        response.body_mut().as_reader(),
        part_file,
        expected_size,
        expected_digest,
        max_bytes,
    )
}

/// Sync, independently rehash, and atomically name one verified part file.
fn promote_verified_part(
    part_path: &Path,
    part_file: &mut File,
    staged_path: &Path,
    expected_size: u64,
    expected_digest: &[u8; 32],
) -> anyhow::Result<()> {
    part_file
        .sync_all()
        .with_context(|| format!("sync downloaded update {}", part_path.display()))?;
    let (size, digest) = sha256_open_file(part_file)?;
    if size != expected_size || !constant_time_eq(&digest, expected_digest) {
        bail!("download changed between streamed and post-sync verification");
    }
    fs::rename(part_path, staged_path).with_context(|| {
        format!(
            "promote verified update {} to {}",
            part_path.display(),
            staged_path.display()
        )
    })
}

/// Exclusive part file that removes itself unless promotion completes.
struct PartFile {
    path: PathBuf,
    file: Option<File>,
    armed: bool,
}

impl PartFile {
    /// Bind cleanup ownership to an open exclusive part file.
    fn new(path: PathBuf, file: File) -> Self {
        Self {
            path,
            file: Some(file),
            armed: true,
        }
    }

    /// Borrow the open part file for streaming and synchronization.
    fn file_mut(&mut self) -> &mut File {
        self.file.as_mut().expect("part file remains open")
    }

    /// Return the exact path owned by this cleanup guard.
    fn path(&self) -> &Path {
        &self.path
    }

    /// Release cleanup ownership after the part path has been promoted.
    fn disarm(&mut self) {
        self.armed = false;
        self.file = None;
    }
}

impl Drop for PartFile {
    /// Close and remove only the owned part path after any failed step.
    fn drop(&mut self) {
        self.file = None;
        if self.armed {
            let _ = fs::remove_file(&self.path);
        }
    }
}

/// Stream bytes into a destination while enforcing exact size and SHA-256.
#[cfg(test)]
fn copy_verified(
    reader: impl Read,
    writer: impl Write,
    expected_size: u64,
    expected_digest: &[u8; 32],
) -> anyhow::Result<()> {
    copy_verified_bounded(
        reader,
        writer,
        expected_size,
        expected_digest,
        MAX_EXECUTABLE_BYTES,
    )
}

/// Stream bytes while enforcing exact size, SHA-256, and a caller ceiling.
fn copy_verified_bounded(
    mut reader: impl Read,
    mut writer: impl Write,
    expected_size: u64,
    expected_digest: &[u8; 32],
    max_bytes: u64,
) -> anyhow::Result<()> {
    let mut hasher = Sha256::new();
    let mut total = 0u64;
    let mut buffer = [0u8; 64 * 1024];
    loop {
        let read = reader.read(&mut buffer).context("read update response")?;
        if read == 0 {
            break;
        }
        total = total
            .checked_add(read as u64)
            .ok_or_else(|| anyhow!("download size overflow"))?;
        if total > expected_size || total > max_bytes {
            bail!("download exceeds the immutable release size");
        }
        hasher.update(&buffer[..read]);
        writer
            .write_all(&buffer[..read])
            .context("write staged update")?;
    }
    let digest: [u8; 32] = hasher.finalize().into();
    if total != expected_size || !constant_time_eq(&digest, expected_digest) {
        bail!("download size or SHA-256 does not match immutable release metadata");
    }
    Ok(())
}

/// Create an exclusive random part file beside the final staged path.
fn create_unique_part(staged_path: &Path) -> anyhow::Result<(PathBuf, File)> {
    for _ in 0..8 {
        let mut random = [0u8; 16];
        getrandom::getrandom(&mut random).context("generate update staging nonce")?;
        let suffix = encode_hex(&random);
        let file_name = staged_path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| anyhow!("staged executable name is not valid UTF-8"))?;
        let part_path = staged_path.with_file_name(format!("{file_name}.{suffix}.part"));
        match OpenOptions::new()
            .write(true)
            .read(true)
            .create_new(true)
            .open(&part_path)
        {
            Ok(file) => return Ok((part_path, file)),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(error).with_context(|| {
                    format!("create exclusive update part {}", part_path.display())
                });
            }
        }
    }
    bail!("could not allocate an exclusive update part file")
}

/// Hash the still-open exclusive staged file for the independent second verification pass.
fn sha256_open_file(file: &mut File) -> anyhow::Result<(u64, [u8; 32])> {
    file.seek(SeekFrom::Start(0))
        .context("rewind staged update for hashing")?;
    let mut hasher = Sha256::new();
    let size = io::copy(file, &mut hasher).context("hash staged update")?;
    Ok((size, hasher.finalize().into()))
}

/// Create a transaction directory only when every update component is a plain directory.
fn ensure_plain_directory(path: &Path) -> anyhow::Result<()> {
    let root = path
        .parent()
        .ok_or_else(|| anyhow!("update transaction directory has no root"))?;
    match fs::symlink_metadata(root) {
        Ok(metadata) if crate::config::paths::is_plain_directory(&metadata) => {}
        Ok(_) => bail!("update root is not a plain directory"),
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            fs::create_dir(root)
                .with_context(|| format!("create update root {}", root.display()))?;
        }
        Err(error) => return Err(error).context("inspect update root"),
    }
    match fs::symlink_metadata(path) {
        Ok(metadata) if crate::config::paths::is_plain_directory(&metadata) => Ok(()),
        Ok(_) => bail!("update transaction path is not a plain directory"),
        Err(error) if error.kind() == io::ErrorKind::NotFound => {
            fs::create_dir(path)
                .with_context(|| format!("create update transaction {}", path.display()))?;
            let metadata = fs::symlink_metadata(path).context("reinspect update transaction")?;
            if crate::config::paths::is_plain_directory(&metadata) {
                Ok(())
            } else {
                bail!("created update transaction is not a plain directory")
            }
        }
        Err(error) => Err(error).context("inspect update transaction"),
    }
}

/// Compare digest bytes without an early-exit mismatch branch.
fn constant_time_eq(left: &[u8; 32], right: &[u8; 32]) -> bool {
    left.iter()
        .zip(right)
        .fold(0u8, |difference, (left, right)| difference | (left ^ right))
        == 0
}

/// Encode random bytes for a filesystem-safe transaction suffix.
fn encode_hex(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut encoded = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        encoded.push(HEX[(byte >> 4) as usize] as char);
        encoded.push(HEX[(byte & 0x0f) as usize] as char);
    }
    encoded
}
