//! Projection of the core's safe-share snapshot into terminal settings.

use super::*;

/// Project the settings the terminal renders out of a full safe-share snapshot.
///
/// `pub(crate)` rather than `pub(super)` for one reason: [`CoreConfig`] deliberately has no
/// `Default`, so this is the only way to build one, and the store's own tests need a projection to
/// drive its edit-row rules with. It stays crate-internal — the UI receives projections, it does
/// not make them.
pub(crate) fn core_config_from_proto(cfg: &SharedConfig) -> CoreConfig {
    let a = &cfg.trading.auto_start;
    let a2 = &cfg.trading.auto_start_2;
    let b = &cfg.visual.blink_config;
    let t = &cfg.trading;
    let m = &cfg.trading.auto_manage_lev;
    let sig = &cfg.signals;
    let hotkeys = &cfg.ui.hotkeys_config;
    let strat_buttons = &cfg.trading.manual_strats_config;
    let v = &cfg.visual;
    let u = &cfg.ui;
    let sc = &cfg.signals.signal_config;
    let shots = &cfg.trading.send_shots_config;
    let oc = &cfg.trading.orders_control;
    let mo = &cfg.trading.multi_orders;
    CoreConfig {
        // The list verbatim: its separator rules live with the readers — see
        // `feed::fav_markets_list` — so the projection carries the core's own string unchanged.
        fav_markets: t.fav_markets.clone(),
        special: SpecialSettings {
            log_level: t.log_level,
            auto_delete_logs: t.auto_delete_logs,
            chart_clean_up_time: t.chart_clean_up_time,
            max_orders: t.max_orders,
            unlimited_orders: t.unlimited_orders,
            random_price: t.random_price,
            correct_order_price: t.correct_order_price,
            use_book_ticker: t.use_book_ticker,
            m_avg_use_vol_weight: t.m_avg_use_vol_weight,
            auto_buy_bnb: t.auto_buy_bnb,
            auto_buy_bnb_level: t.auto_buy_bnb_level,
            auto_buy_bnb_volume: t.auto_buy_bnb_volume,
            auto_reduce_order: t.auto_reduce_order,
            auto_close_zero_pos: t.auto_close_zero_pos,
            auto_lower_lev: t.auto_lower_lev,
            use_websocket_api: t.use_websocket_api,
            futures_rules: t.futures_rules,
            iceberg_step: t.iceberg_step,
            sell_x2_level: t.sell_x2_level,
            no_trades_markets_text: t.no_trades_markets_text.clone(),
            multi_commands: t.multi_commands,
            h_pos_black_list_text: t.h_pos_black_list_text.clone(),
            liq_control: oc.liq_control,
            ignore_replacing_bug: oc.ignore_replacing_bug,
            ignore_protection: oc.ignore_protection,
            orders_control_active: oc.active,
            h_pos_report: oc.h_pos_report,
            h_pos_auto_sell: oc.h_pos_auto_sell,
            send_shots: shots.may_send,
            profit_abs: shots.profit_abs,
            profit_pers: shots.profit_pers,
            profit_session: shots.profit_session,
            send_negative: shots.send_negative,
            send_public: shots.send_public,
            time_scale: shots.time_scale,
            price_scale: shots.price_scale,
        },
        telegram: TelegramSettings {
            pump_channel: sig.pump_channel.clone(),
            pump_channels: sig.pump_channels.clone(),
            multi_channels: sig.multi_channels,
            more_then_1_channel: sig.more_then_1_channel,
            listen_moon_channel: sig.listen_moon_channel,
            use_moon_bl: t.use_moon_bl,
        },
        auto_buy: AutoBuySettings {
            monitor_clipboard: sig.monitor_clipboard,
            clipboard_auto_buy: sig.clipboard_auto_buy,
            lower_case_token_cbd: sig.lower_case_token_cbd,
            look_full_link_cbd: sig.look_full_link_cbd,
            advanced_filter_clipboard: sig.advanced_filter_clipboard,
            telegram_auto_buy: sig.telegram_auto_buy,
            lower_case_token_tlg: sig.lower_case_token_tlg,
            look_full_link_tlg: sig.look_full_link_tlg,
            advanced_filter: sig.advanced_filter,
            dont_buy_reply: sig.dont_buy_reply,
            dont_buy_forward: t.dont_buy_forward,
            msg_keywords_long: sig.msg_keywords_long.clone(),
            msg_keywords_short: sig.msg_keywords_short.clone(),
            msg_black_words: sig.msg_black_words.clone(),
            msg_token_tags: sig.msg_token_tags.clone(),
            lower_price_words: sig.lower_price_words.clone(),
            use_keywords: sc.use_keywords,
            buy_key_dist: sc.buy_key_dist,
            use_black_words: sc.use_black_words,
            use_words_count: sc.use_words_count,
            words_count: sc.words_count,
            use_lower_price_words: sc.use_lower_price_words,
            x_lower_price: sc.x_lower_price,
            x_found_price: sc.x_found_price,
            buy_if_price_found: sc.buy_if_price_found,
            use_price: sc.use_price,
            use_stops: sc.use_stops,
            only_1_token: sc.only_1_token,
            use_token_tags: sc.use_token_tags,
            tokens_no_tags: sc.tokens_no_tags,
            token_links: sc.token_links,
            special_formats: sc.special_formats,
            auto_cancel_lower_buy: t.auto_cancel_lower_buy,
        },
        interface: InterfaceSettings {
            buy_on_enter: t.buy_on_enter,
            dbl_click_panic_sell: t.dbl_click_panic_sell,
            chart_split_zones: t.chart_split_zones,
            draw_stop: t.draw_stop,
            pending_orders_spread: t.pending_orders_spread,
            pending_orders_spread_h_delta: t.pending_orders_spread_h_delta,
            hide_forum_label: v.hide_forum_label,
            scrolling_charts: v.scrolling_charts,
            startup_load_charts: v.startup_load_charts,
            hide_right_chart_panel: v.hide_right_chart_panel,
            left_chart_info: v.left_chart_info,
            show_iceberg: v.show_iceberg,
            show_orders_captions: v.show_orders_captions,
            orders_captions_lower: v.orders_captions_lower,
            hide_pnl: v.hide_pnl,
            hide_buy_button: v.hide_buy_button,
            hide_cashback_button: v.hide_cashback_button,
            remember_chart_buttons: v.remember_chart_buttons,
            scale_tool: v.show_filters.scale_tool,
            icon_selection: v.icon_selection,
            price_line_width: v.colors.price_line_width,
            panic_sell_opacity: v.panic_sell_opacity,
            glass_opacity: v.glass_opacity,
            book_cumulative_opacity: v.book_cumulative_opacity,
            book_orders_opacity: v.book_orders_opacity,
            book_orders_width: v.book_orders_width,
            play_signal_sound: sig.play_signal_sound,
            signal_sound: sig.signal_sound,
            confirm_close: u.confirm_close,
            hide_demo_button: u.hide_demo_button,
            auto_show_on_signal: sig.auto_show_on_signal,
            show_market_captions: v.show_market_captions,
            show_usd_on_charts: v.show_usd_on_charts,
            show_detects_tool: v.show_detects_tool,
            auto_request_charts: v.auto_request_charts,
            new_markets_max_scale: v.new_markets_max_scale,
            new_markets_on_top: u.new_markets_on_top,
            use_last_detect_caption: sig.use_last_detect_caption,
            full_screen_prevent_signals: sig.full_screen_prevent_signals,
            pending_buy_price: t.pending_buy_price,
            hide_cashback_info: t.cashback_settings.hide_info,
        },
        signals: SignalsSettings {
            play_sell_alert: sig.play_sell_alert,
            sell_alert_level: sig.sell_alert_level,
            signal_sound_2: sig.signal_sound_2,
            play_buy_alert: sig.play_buy_alert,
            buy_alert_level: sig.buy_alert_level,
            buy_signal_sound: sig.buy_signal_sound,
        },
        auto_start: AutoStartSettings {
            auto_start: a.auto_start,
            auto_detect_on: a.auto_detect_on,
            strategies_on: a.strategies_on,
            remember_state: a.remember_state,
            auto_update: a.auto_update,
            dont_wait_sells: a.dont_wait_sells,
            work_time: a.work_time,
            work_time_from_min: day_fraction_to_minutes(a.work_time_from),
            work_time_to_min: day_fraction_to_minutes(a.work_time_to),
            auto_stop_if_loss: a.auto_stop_if_loss,
            auto_stop_loss: a.auto_stop_loss,
            stop_trades: a.stop_trades,
            sell_if_loss: a.sell_if_loss,
            auto_stop_if_loss_hours: a.auto_stop_if_loss_hours,
            auto_stop_hours_val: a.auto_stop_hours_val,
            stop_hours: a.stop_hours,
            stop_hours_trades: a.stop_hours_trades,
            ignore_emulator: a.ignore_emulator,
            reset_session: a2.reset_session,
            rs_hours: a2.rs_hours,
            max_session_cap: a2.max_session_cap,
            panic_btc: a.panic_btc,
            panic_btc_delta: a.panic_btc_delta,
            panic_btc_delta_up: a.panic_btc_delta_up,
            panic_market: a.panic_market,
            panic_market_delta: a.panic_market_delta,
            restart_on_market: a2.restart_on_market,
            btc_higher_then: a2.btc_higher_then,
            btc_lower_then: a2.btc_lower_then,
            market_higher_then: a2.market_higher_then,
            auto_stop_on_errors: a.auto_stop_on_errors,
            errors_level: a.errors_level,
            sell_all_on_errors: a.sell_all_on_errors,
            restart_after_err: a.restart_after_err,
            restart_err_time: a.restart_err_time,
            auto_stop_on_ping: a.auto_stop_on_ping,
            ping_level: a.ping_level,
            sell_all_on_ping: a.sell_all_on_ping,
            restart_after_ping: a.restart_after_ping,
            restart_ping_time: a.restart_ping_time,
        },
        btc_blink: BtcBlinkSettings {
            blink_btc: b.blink_btc,
            blink_btc_delta: b.blink_btc_delta,
            blink_btc_delta_up: b.blink_btc_delta_up,
            alarm_btc: b.alarm_btc,
            alarm_type: b.alarm_type,
        },
        general: GeneralSettings {
            take_profit_on: t.use_g_take_profit,
            take_profit_pct: t.g_take_profit,
            trailing_on: t.trailing_stop,
            trailing_pct: t.trailing_drop,
            vstop_on: t.panic_if_vol_drop,
            vol_drop_level: t.vol_drop_level,
            buy_iceberg: t.buy_iceberg,
            sell_iceberg: t.sell_iceberg,
            blacklist_on: t.use_coins_black_list,
            blacklist_text: t.coins_black_list_text.clone(),
            exclude_blacklisted_from_deltas: t.exclude_black_list_delta,
        },
        order_rules: OrderRulesSettings {
            trailing_float: t.trailing_float,
            auto_sell_partial: t.auto_sell_partial,
            auto_cancel_buy_order: t.auto_cancel_buy_order,
            cancel_buy_on_sell_fill: t.cancel_buy_on_sell_fill,
            dont_buy_new_coins: t.dont_buy_new_coins,
            deltas_by_trades: t.deltas_by_trades,
            analyze_on_start: sig.load_deep_history,
        },
        gestures: GestureSettings {
            buy_set_click: mo.buy_set_click,
            short_set_click: mo.short_set_click,
            pending_order_set_click: t.pending_order_set_click,
            pending_short_set_click: mo.pending_short_set_click,
            same_hotkeys_for_move: mo.same_hotkeys_for_move,
            buy_move_click: mo.buy_move_click,
            short_buy_move_click: mo.short_buy_move_click,
            replace_buy_kind: mo.replace_buy_kind,
            sell_move_click: mo.sell_move_click,
            short_sell_move_click: mo.short_sell_move_click,
            replace_sell_kind: mo.replace_sell_kind,
            buy_move_click_2: mo.buy_move_click_2,
            short_buy_move_click_2: mo.short_buy_move_click_2,
            replace_buy_kind_2: mo.replace_buy_kind_2,
            sell_move_click_2: mo.sell_move_click_2,
            short_sell_move_click_2: mo.short_sell_move_click_2,
            replace_sell_kind_2: mo.replace_sell_kind_2,
        },
        leverage: LeverageSettings {
            auto_max_order: m.auto_max_order,
            auto_lev_up: m.auto_lev_up,
            auto_isolated: m.auto_isolated,
            auto_cross: m.auto_cross,
            tlg_report: m.tlg_report,
            auto_fix_lev: m.auto_fix_lev,
            fix_lev: m.fix_lev,
            lev_control: t.auto_lev_control.clone(),
        },
        manual: ManualSettings {
            order_sizes: hotkeys.o_size,
            // `saturating_sub`, not `-`: `b_num` is untrusted wire `i32`, and this repo runs with
            // `debug-assertions = false` even in dev (root `Cargo.toml`), so a corrupt `i32::MIN`
            // would otherwise wrap silently to `i32::MAX` and clamp to slot 5 — the LARGEST
            // preset — instead of being caught, on a money-adjacent field.
            order_size_sel: hotkeys.b_num.saturating_sub(1).clamp(0, 5) as usize,
            strat_names: t.manual_strats_names.clone(),
            strat_buttons: CoreStratButtons {
                use_buttons: strat_buttons.use_buttons,
                show_button: strat_buttons.show_button,
                hot_keys: strat_buttons.hot_keys,
            },
            core_hotkeys: CoreHotkeyLayout {
                order_size: hotkeys.o_keys,
                sell_preset: hotkeys.s_keys,
                named: [
                    (CoreHotkeyAction::CancelBuy, hotkeys.cancel_buy),
                    (CoreHotkeyAction::PanicSell, hotkeys.panic_sell),
                    (CoreHotkeyAction::JoinSells, hotkeys.join_sells),
                    (CoreHotkeyAction::SwitchCharts, hotkeys.switch_charts),
                    (CoreHotkeyAction::ReloadBook, hotkeys.reload_book),
                    (CoreHotkeyAction::NewLong, hotkeys.new_long),
                    (CoreHotkeyAction::NewShort, hotkeys.new_short),
                    (CoreHotkeyAction::SplitOrder, hotkeys.split_order),
                    (CoreHotkeyAction::ShiftBuyUp, hotkeys.shift_buy_up),
                    (CoreHotkeyAction::ShiftBuyDown, hotkeys.shift_buy_down),
                    (CoreHotkeyAction::ShiftSellUp, hotkeys.shift_sell_up),
                    (CoreHotkeyAction::ShiftSellDown, hotkeys.shift_sell_down),
                    (CoreHotkeyAction::MakeShot, hotkeys.make_shot),
                    (CoreHotkeyAction::MakeShotBot, hotkeys.make_shot_bot),
                    (CoreHotkeyAction::ReloadChart, hotkeys.reload_chart),
                    (CoreHotkeyAction::ScalePlus, hotkeys.scale_plus),
                    (CoreHotkeyAction::ScaleMinus, hotkeys.scale_minus),
                    (CoreHotkeyAction::SellPlus, hotkeys.sell_plus),
                    (CoreHotkeyAction::SellMinus, hotkeys.sell_minus),
                    (CoreHotkeyAction::SpyMode, hotkeys.spy_mode),
                    (CoreHotkeyAction::ShowCharts, hotkeys.show_charts),
                    (CoreHotkeyAction::SplitOrderX, hotkeys.split_order_x),
                    (CoreHotkeyAction::SwitchFigure, hotkeys.switch_figure),
                    (CoreHotkeyAction::FitSells, hotkeys.fit_sells),
                    (CoreHotkeyAction::PanicSellOne, hotkeys.panic_sell_one),
                    (CoreHotkeyAction::CancelAllBuys, hotkeys.cancel_all_buys),
                    (CoreHotkeyAction::Broadcast, hotkeys.broadcast),
                ],
            },
            ignore_strat_sell_price: t.ignore_strat_sell_price,
            use_lev_for_take: t.use_lev_for_take,
        },
    }
}
