//! Stable GitHub release discovery and verified update downloads.
//!
//! This module deliberately stops at a verified staged executable. Process coordination,
//! replacement, restart, and rollback belong to the Windows GPUI shell.

use std::path::PathBuf;
use std::time::Duration;

mod discovery;
mod download;
mod release;

pub use discovery::{DiscoveryError, DiscoveryResult, DiscoveryRetry, ReleaseDiscovery};
pub use release::{
    AvailableRelease, BuildIdentity, ReleaseAsset, ReleaseVersion, UpdateEligibility,
};

#[cfg(test)]
mod tests;

const RELEASES_URL: &str = "https://api.github.com/repos/Moonbot-Tech/MoonTerminal/releases";

/// Synchronous GitHub client intended for a dedicated background executor.
#[derive(Clone)]
pub struct GitHubReleaseClient {
    agent: ureq::Agent,
    releases_url: String,
}

impl GitHubReleaseClient {
    /// Build a bounded HTTPS-only client for public release metadata and assets.
    ///
    /// Returns:
    ///     Client with a global timeout and bounded redirect chain.
    pub fn new() -> Self {
        Self::build(RELEASES_URL, true)
    }

    /// Build one transport with an explicit release-list endpoint and HTTPS policy.
    ///
    /// Args:
    ///     releases_url: Exact release-list endpoint.
    ///     https_only: Whether the transport rejects all plain-HTTP requests.
    ///
    /// Returns:
    ///     A bounded synchronous GitHub client.
    fn build(releases_url: &str, https_only: bool) -> Self {
        let config = ureq::Agent::config_builder()
            .timeout_global(Some(Duration::from_secs(30)))
            .https_only(https_only)
            .max_redirects(5)
            .http_status_as_error(false)
            .build();
        Self {
            agent: ureq::Agent::new_with_config(config),
            releases_url: releases_url.to_owned(),
        }
    }

    /// Build a loopback-capable client that is absent from production artifacts.
    ///
    /// Args:
    ///     releases_url: Loopback fixture endpoint.
    ///
    /// Returns:
    ///     A test-only client that permits plain HTTP.
    #[cfg(test)]
    fn for_test(releases_url: &str) -> Self {
        Self::build(releases_url, false)
    }

    /// Download an eligible asset into a verified staged executable.
    ///
    /// Args:
    ///     release: Immutable release metadata selected by [`ReleaseDiscovery::scan`].
    ///     nonce: Validated transaction identifier generated by the transaction owner.
    ///
    /// Returns:
    ///     The staged path after streamed and post-sync SHA-256 verification on one open handle.
    pub fn download_verified(
        &self,
        release: &AvailableRelease,
        nonce: &str,
    ) -> anyhow::Result<PathBuf> {
        download::download_verified(self, release, nonce)
    }
}

impl Default for GitHubReleaseClient {
    /// Build the production GitHub release client.
    fn default() -> Self {
        Self::new()
    }
}
