//! Stable GitHub release discovery and verified update downloads.
//!
//! This module deliberately stops at a verified download: the staged Windows executable or the
//! macOS disk image. Process coordination, replacement, restart, and rollback belong to the
//! Windows GPUI shell; on macOS the shell only opens the image.

use std::path::PathBuf;
use std::time::Duration;

mod discovery;
mod download;
mod release;

pub use discovery::{DiscoveryError, DiscoveryResult, DiscoveryRetry, ReleaseDiscovery};
pub use release::{
    AvailableRelease, BuildIdentity, ReleaseAsset, ReleaseVersion, UpdateEligibility,
};

#[cfg(test)]
mod tests;

const RELEASES_URL: &str = "https://api.github.com/repos/Moonbot-Tech/MoonTerminal/releases";

/// Synchronous GitHub client intended for a dedicated background executor.
#[derive(Clone)]
pub struct GitHubReleaseClient {
    agent: ureq::Agent,
    releases_url: String,
}

impl GitHubReleaseClient {
    /// Build a bounded HTTPS-only client for public release metadata and assets.
    ///
    /// Returns:
    ///     Client with a global timeout and bounded redirect chain.
    pub fn new() -> Self {
        Self::build(RELEASES_URL, true)
    }

    /// Build one transport with an explicit release-list endpoint and HTTPS policy.
    ///
    /// Args:
    ///     releases_url: Exact release-list endpoint.
    ///     https_only: Whether the transport rejects all plain-HTTP requests.
    ///
    /// Returns:
    ///     A bounded synchronous GitHub client.
    fn build(releases_url: &str, https_only: bool) -> Self {
        let config = ureq::Agent::config_builder()
            .timeout_global(Some(Duration::from_secs(30)))
            .https_only(https_only)
            .max_redirects(5)
            .http_status_as_error(false)
            .build();
        Self {
            agent: ureq::Agent::new_with_config(config),
            releases_url: releases_url.to_owned(),
        }
    }

    /// Build a loopback-capable client that is absent from production artifacts.
    ///
    /// Args:
    ///     releases_url: Loopback fixture endpoint.
    ///
    /// Returns:
    ///     A test-only client that permits plain HTTP.
    #[cfg(test)]
    fn for_test(releases_url: &str) -> Self {
        Self::build(releases_url, false)
    }

    /// Download an eligible asset into a verified staged executable.
    ///
    /// Args:
    ///     release: Immutable release metadata selected by [`ReleaseDiscovery::scan`].
    ///     nonce: Validated transaction identifier generated by the transaction owner.
    ///
    /// Returns:
    ///     The staged path after streamed and post-sync SHA-256 verification on one open handle.
    pub fn download_verified(
        &self,
        release: &AvailableRelease,
        nonce: &str,
    ) -> anyhow::Result<PathBuf> {
        download::download_verified(self, release, nonce)
    }

    /// Download an eligible asset to an exact destination, such as the macOS disk image.
    ///
    /// Args:
    ///     release: Immutable release metadata selected by [`ReleaseDiscovery::scan`].
    ///     dest: Final file path; its parent directory is created when missing.
    ///
    /// Returns:
    ///     `dest` after the same size and SHA-256 verification as [`Self::download_verified`].
    pub fn download_verified_to(
        &self,
        release: &AvailableRelease,
        dest: &std::path::Path,
    ) -> anyhow::Result<PathBuf> {
        download::download_verified_to(self, release, dest)
    }
}

/// File name the macOS disk image of one release is saved under.
///
/// Args:
///     version: Release version the image installs.
///
/// Returns:
///     `MoonTerminal-<major>.<minor>.<patch>.dmg`, distinct per release so an older image in the
///     same folder is never mistaken for the new one.
pub fn installer_image_file_name(version: ReleaseVersion) -> String {
    format!(
        "MoonTerminal-{}.{}.{}.dmg",
        version.major, version.minor, version.patch
    )
}

/// Path in the user's Downloads folder where one release's disk image is saved.
///
/// Args:
///     version: Release version the image installs.
///
/// Returns:
///     [`crate::config::paths::user_download_path`] for [`installer_image_file_name`], or
///     `None` when no Downloads folder can be resolved.
pub fn installer_image_download_path(version: ReleaseVersion) -> Option<PathBuf> {
    crate::config::paths::user_download_path(&installer_image_file_name(version))
}

impl Default for GitHubReleaseClient {
    /// Build the production GitHub release client.
    fn default() -> Self {
        Self::new()
    }
}
