//! Cold-process coverage for dictionary lookups that previously overflowed default test stacks.

use std::process::Command;

/// Removing a locale guard from a previously crashing test must fail even when another test
/// already warmed the dictionary in this process. Each child runs exactly one test with the
/// default Rust test-thread stack and its own uninitialized translation backend.
#[test]
fn localized_tests_initialize_on_default_stacks() {
    let binary = std::env::current_exe().expect("terminal test binary");
    for test in COLD_LOOKUPS {
        let output = Command::new(&binary)
            .args([test, "--exact", "--nocapture"])
            .env_remove("RUST_MIN_STACK")
            .output()
            .expect("spawn cold locale test");
        assert!(
            output.status.success(),
            "{test} failed on a cold default stack: {}\n{}\n{}",
            output.status,
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr),
        );
        assert!(
            String::from_utf8_lossy(&output.stdout).contains("1 passed;"),
            "{test} must remain an exact test target, not an empty successful run",
        );
    }
}

/// Exact targets that exited with STATUS_STACK_OVERFLOW when each was run cold, before guards.
/// Keep these independent of source scanning so moving or removing a guard cannot hide a target.
const COLD_LOOKUPS: &[&str] = &[
    "analytics::profit_monitor::tests::exchange_rows_group_by_venue_identity_not_by_caption",
    "analytics::profit_monitor::tests::idle_rows_cover_active_cores_only_and_only_by_core",
    "analytics::profit_monitor::tests::merged_rows_carry_the_newest_trade_of_their_cores",
    "analytics::purge::tests::no_legacy_rows_means_no_caveat",
    "analytics::purge::tests::report_rows_only_has_one_progress_step_and_distinct_empty_copy",
    "analytics::purge::tests::the_count_line_states_both_scopes",
    "analytics::purge::tests::the_legacy_caveat_appears_whenever_there_are_legacy_rows",
    "analytics::purge::tests::zero_trades_is_stated_not_counted",
    "analytics::summary::tests::insight_sentence_unit_follows_the_metric",
    "analytics::toolbar::tests::a_read_failure_is_never_collapsed",
    "analytics::toolbar::tests::the_notice_starts_collapsed_and_opens_only_on_request",
    "analytics::tuner::coins::picker::tests::a_pending_tick_claims_no_date_and_no_core",
    "analytics::tuner::coins::picker::tests::the_field_follows_the_edit_not_the_saved_list",
    "analytics::tuner::kpi::tests::an_open_tail_follows_the_closed_profit_in_brackets",
    "analytics::tuner::ticks::tests::every_answer_states_its_out_of_sample_status",
    "chartdx::engine::tests::a_stale_label_offset_is_reclamped_before_the_wheel_moves_it",
    "chartdx::engine::tests::reveal_after_a_hidden_book_update_refreshes_center_and_live_edge",
    "chartdx::ruler::tests::a_duration_reads_in_its_two_largest_units",
    "chartdx::ruler::tests::the_move_line_is_signed_by_the_drag_direction",
    "chartdx::ruler::tests::the_volume_line_prefers_a_whole_split_then_the_candles",
    "chartdx::text::captions::tests::filter_header_and_lines_share_one_stack",
    "chartdx::text::captions::tests::mixed_filter_column_keeps_its_header_above_entries_inside_a_short_pane",
    "chartdx::text::captions::tests::overflowing_filter_cells_keep_the_header_inside_the_bottom_band",
    "chartdx::text::labels::tests::a_caption_keeps_its_prefix_beside_its_value",
    "chartdx::text::labels::tests::a_coin_figure_is_marked_when_the_aggregates_answered",
    "chartdx::text::labels::tests::a_figure_below_the_colour_threshold_prints_without_a_sign",
    "chartdx::text::labels::tests::a_handed_trade_states_its_strategy_line_and_exit",
    "chartdx::text::labels::tests::a_long_filter_column_shows_its_window_indicators_and_the_true_total",
    "chartdx::text::labels::tests::a_signed_figure_carries_its_sign_for_coloring",
    "chartdx::text::labels::tests::a_tick_below_the_printed_precision_does_not_change_the_caption",
    "chartdx::text::labels::tests::a_zero_core_pnl_prints_nothing",
    "chartdx::text::labels::tests::a_zero_session_still_prints_but_an_absent_one_does_not",
    "chartdx::text::labels::tests::an_uncovered_period_is_marked",
    "chartdx::text::labels::tests::an_unresolved_field_occupies_no_row",
    "chartdx::text::labels::tests::re_running_with_identical_inputs_reports_no_change",
    "chartdx::text::labels::tests::the_bar_is_the_side_s_share_and_a_silent_market_has_none",
    "chartdx::text::labels::tests::the_caption_address_survives_a_skipped_neighbour",
    "chartdx::text::labels::tests::the_caption_flag_prefixes_the_field_name",
    "chartdx::text::labels::tests::the_detect_strategy_names_itself",
    "chartdx::text::labels::tests::the_heading_names_the_period_without_any_reading",
    "chartdx::text::labels::tests::the_pnl_percentage_is_weighted_by_what_each_order_spent",
    "chartdx::text::labels::tests::the_prefix_switch_drops_the_period_and_keeps_the_name",
    "chartdx::text::labels::tests::the_prefix_switch_still_removes_a_plain_caption",
    "chartdx::text::labels::tests::the_preview_answers_for_every_field",
    "chartdx::text::labels::tests::the_preview_skips_a_hidden_caption_and_prints_the_name",
    "chartdx::text::labels::tests::the_time_scale_badge_prints_the_span_as_a_compact_duration",
    "chartdx::text::labels::tests::the_volume_total_is_the_sum_of_the_two_sides",
    "chartdx::text::labels::tests::two_captions_can_read_different_bases",
    "chartdx::text::tick_volume::tests::a_candle_only_readout_stacks_into_a_narrow_pane",
    "chartdx::text::tick_volume::tests::an_unnameable_bucket_width_drops_the_period_not_the_figure",
    "chartdx::text::tick_volume::tests::candle_alone_draws_without_the_tick_heading",
    "chartdx::text::tick_volume::tests::candle_volume_is_a_separate_labelled_aggregate",
    "chartdx::text::tick_volume::tests::combined_default_readout_fits_narrow_panes_at_multiple_dpis",
    "chartdx::text::tick_volume::tests::equal_sell_prints_keep_count_value_and_quote",
    "chartdx::text::tick_volume::tests::fit_honors_measured_width_height_and_exact_boundary",
    "chartdx::text::tick_volume::tests::increased_font_respects_the_combined_readout_height_boundary",
    "chartdx::text::tick_volume::tests::narrow_backdrops_stay_inside_offset_panes_at_multiple_dpis",
    "chartdx::text::tick_volume::tests::narrow_dock_stacks_both_counts_and_exact_ranges",
    "chartdx::text::tick_volume::tests::scientific_fallback_round_trips_extremes_and_adjacent_values",
    "chartdx::text::tick_volume::tests::sides_bucket_prints_both_sides_under_its_period",
    "chartdx::text::tick_volume::tests::stacked_candle_keeps_its_unit_reachable",
    "chartdx::text::tick_volume::tests::wide_readout_keeps_original_lines",
    "conn_diag::tests::key_unparsable_wording_distinguishes_blank_from_pasted_garbage",
    "conn_diag::tests::only_no_response_verdicts_receive_a_mode_suggestion",
    "conn_diag::tests::unparsed_datagrams_do_not_use_the_silent_wording",
    "controls::core_combo::tests::menu_sections_are_unknown_first_alphabetical_and_member_stable",
    "panels::assets::balances::tests::a_hyperliquid_fold_carries_its_caveat",
    "panels::assets::balances::tests::an_excluded_core_is_named_in_facts_and_tooltip",
    "panels::assets::balances::tests::facts_always_name_the_core_count",
    "panels::assets::balances::tests::facts_list_every_reason_in_priority_order",
    "panels::assets::balances::tests::tooltip_carries_every_fact_that_can_clip",
    "panels::assets::balances::tests::tooltip_shows_dash_when_nothing_reported",
    "panels::assets::balances::tests::two_cores_on_one_account_are_one_account_in_the_footer",
    "panels::assets::table::tests::the_columns_follow_the_selected_fields_exactly",
    "panels::assets::table::tests::the_title_less_actions_column_never_stretches",
    "panels::chart::shot::header::tests::a_positive_window_magnitude_is_printed_without_an_invented_sign",
    "panels::chart::shot::header::tests::an_unknown_window_is_omitted_instead_of_becoming_a_zero",
    "panels::chart::shot::header::tests::group_boundaries_fall_on_the_stamp_and_three_hour_field_only",
    "panels::chart::shot::header::tests::identity_stays_in_the_head_and_fifteen_minutes_is_the_first_window_to_clip",
    "panels::chart::shot::header::tests::only_movement_figures_are_primary_runs",
    "panels::chart::shot::header::tests::the_builder_emits_no_separator_glyphs",
    "panels::chart::shot::header::tests::the_scale_badge_follows_the_chart_convention_and_view_order",
    "panels::chart::shot::header::tests::the_time_scale_follows_the_y_scale_in_the_chart_spelling",
    "panels::core_status::ordering::tests::flat_lines_partitions_each_input_row_once_by_venue_identity",
    "panels::core_status::presentation::tests::an_expired_key_reads_as_a_word",
    "panels::core_status::presentation::tests::perpetual_api_keys_keep_an_explanatory_tooltip",
    "panels::core_status::problems::tests::a_truncated_list_is_stated_even_when_every_core_answered",
    "panels::core_status::problems::tests::an_unknown_category_is_shown_as_its_raw_byte",
    "panels::core_status::problems::tests::the_channel_test_opens_only_for_one_connected_core",
    "panels::core_status::startup::tests::an_absent_upstream_value_contributes_no_fact_line",
    "panels::core_status::startup::tests::problem_diagnostic_keeps_verdict_and_socket_facts_on_the_failed_attempt",
    "panels::core_status::time_offset::tests::an_unmeasured_status_reports_no_offset_line",
    "panels::core_status::time_offset::tests::the_tooltip_is_built_from_the_facts_not_restated",
    "panels::core_status::time_offset::tests::unknown_never_renders_as_utc",
    "panels::news::clip::tests::the_delay_is_the_latest_service_mark_not_the_sum",
    "panels::orders::table::tests::every_order_column_descriptor_is_sortable",
    "panels::registry::tests::every_registry_panel_has_a_localized_label",
    "panels::report::selection::tests::clipboard_tsv_uses_visual_column_and_row_order_without_embedded_delimiters",
    "panels::report::totals::tests::a_clipped_facts_diagnostic_survives_in_the_row_tooltip",
    "panels::report::totals::tests::a_current_rate_total_is_labelled_apart_from_historical_profit",
    "panels::report::totals::tests::a_loaded_empty_result_promotes_no_figure",
    "panels::report::totals::tests::a_partial_headline_figure_is_stated_in_the_untrusted_tone",
    "panels::report::totals::tests::a_single_currency_breakdown_is_bracketed_on_both_sides",
    "panels::report::totals::tests::a_stall_leads_the_tail_and_the_counts_close_it",
    "panels::report::totals::tests::a_unified_usdt_total_outranks_the_currency_it_was_built_from",
    "panels::report::totals::tests::an_absent_snapshot_states_the_read_rather_than_a_zero",
    "panels::report::totals::tests::average_order_fact_clips_between_volume_and_open_positions",
    "panels::report::totals::tests::open_positions_fact_clips_before_traded_volume",
    "panels::report::totals::tests::partial_single_currency_volume_is_stated_and_marked_rather_than_withheld",
    "panels::report::totals::tests::partial_traded_volume_keeps_the_known_bucket_and_spells_its_shortfall",
    "panels::report::totals::tests::single_quote_volume_keeps_its_persisted_native_amount",
    "panels::report::totals::tests::the_caption_states_the_order_count_and_the_tail_no_longer_does",
    "panels::report::totals::tests::the_currency_breakdown_is_wrapped_in_one_pair_of_brackets",
    "panels::report::totals::tests::the_head_is_the_caption_and_one_money_figure",
    "panels::report::totals::tests::the_shown_rows_tally_is_pinned_right_rather_than_clipped",
    "panels::report::totals::tests::the_tooltip_spells_out_the_caption_count",
    "panels::report::totals::tests::traded_volume_is_unsigned_complete_separated_and_tooltip_recoverable",
    "panels::report::totals::tests::traded_volume_keeps_its_known_buckets_and_is_absent_only_with_nothing_provable",
    "panels::report::totals::tests::worker_health_is_stated_outside_every_quote_scope_branch",
    "panels::report::window::tests::report_title_names_only_an_explicit_sole_core",
    "settings::connections::columns::tests::caps_match_the_text_column_contract_at_each_font_scale",
    "settings::connections::columns::tests::growth_and_tooltips_match_the_text_column_contract",
    "settings::connections::columns::tests::name_is_the_only_uncapped_growing_column_with_the_widest_narrow_width",
    "settings::connections::columns::tests::total_trigger_fits_every_localized_option_at_each_zoom",
    "settings::connections::columns::tests::widths_follow_the_frozen_per_column_policy",
    "settings::connections::tests::flatten_entries_group_known_names_and_keep_unknown_first",
    "settings::connections::tests::pending_section_selects_only_unsaved_cores_and_excludes_them_from_groups",
    "settings::hotkeys::clash::tests::a_builtin_beats_the_slots_below_it_and_loses_to_the_eight_above",
    "settings::hotkeys::clash::tests::a_conditional_chart_layer_shares",
    "settings::hotkeys::clash::tests::a_lower_layer_is_told_it_loses_and_the_upper_one_that_it_takes",
    "settings::hotkeys::clash::tests::a_shared_placement_gesture_names_a_winner_and_a_loser",
    "settings::hotkeys::clash::tests::move_rows_rank_by_the_dispatchers_pairs_not_by_row_order",
    "settings::hotkeys::clash::tests::the_dead_figure_delete_gestures_are_reported_dead",
    "settings::hotkeys::clash::tests::the_documented_delete_fallback_is_exempt_and_nothing_else_is",
    "settings::hotkeys::clash::tests::the_shipped_defaults_leave_nothing_dead",
    "settings::hotkeys::pull_gestures::tests::a_core_value_of_none_arrives_as_none",
    "settings::hotkeys::pull_gestures::tests::a_mirrored_short_row_takes_the_long_gesture_not_the_stale_short_field",
    "settings::hotkeys::pull_gestures::tests::an_unknown_ordinal_is_refused_rather_than_guessed",
    "settings::hotkeys::pull_gestures::tests::applying_a_long_gesture_leaves_the_short_row_the_core_did_not_change",
    "settings::hotkeys::pull_gestures::tests::every_row_the_preview_offers_is_one_the_apply_writes",
    "settings::hotkeys::pull_gestures::tests::turning_the_mirror_off_re_aims_the_short_rows_it_makes_live",
    "settings::hotkeys::pull_gestures::tests::turning_the_mirror_on_re_aims_the_short_rows_it_hides",
    "settings::hotkeys::registry::tests::the_gesture_marks_name_exactly_the_gestures_the_pull_writes",
    "shell::workspace::tests::problem_hover_keeps_connection_stage_and_complete_startup_diagnostics",
    "shell::workspace::tests::rail_summary_segments_still_compose_the_frozen_summary_sentence_per_locale",
    "strategies::tree::cache::tests::venue_digest_is_stable_for_unchanged_ordered_input",
    "strategies::tree::cache::tests::venue_digest_moves_for_every_grouping_and_caption_input",
    "workspace::scope_marker::tests::line_joins_the_footer_facts_without_a_leading_separator",
    "workspace::scope_marker::tests::the_footer_head_never_joins_the_clipping_tail",
    "workspace::tests::roster_groups_reported_exchanges_and_keeps_unavailable_rows",
];
